(setq hello "world")
(message "hello=%s" hello)
(message "hello1=%s" hello)
(message "hello2=%s" hello)
(message "hello3=%s" hello)
(message "hello4=%s" hello)
(message "hello5=%s" hello)
(message "hello6=%s" hello)
(message "hello7=%s" hello)
(message "hello8=%s" hello)
(message "hello9=%s" hello)
(message "hello1=%s" hello)
(message "hello1=%s" hello)
(message "hello1=%s" hello)
(message "hello1=%s" hello)
(message "hello1=%s" hello)
(message "hello1=%s" hello)
(debug-print "hello")
(debug-print "hello1")
(debug-print "hello2")
(debug-print "hello3")
(debug-print 'hello4')

<div>hello world</div>
